@HOST=https://claude.ai/api
#  注意替换
@SESSION=你的 SessionKey
# 注意替换
@ORGID=你的 orgId

### 创建新的对话
POST {{HOST}}/organizations/{{ORGID}}/chat_conversations
Content-Type: application/json
Accept: */*
Cookie: sessionKey={{SESSION}}

{
  "uuid": "55b60f60-2088-11ee-b7b5-fbf72517325a", 
  "name": "测试"
}

### 获取历史对话
GET {{HOST}}/organizations/{{ORGID}}/chat_conversations
Accept: application/json
Cookie: sessionKey={{SESSION}}

### 删除历史对话
DELETE {{HOST}}/organizations/{{ORGID}}/chat_conversations/9cfa6570-208c-11ee-b95f-f96348d3a299
Content-Type: application/json
Accept: */*
Cookie: sessionKey={{SESSION}}

### 发送消息
POST {{HOST}}/append_message
Content-Type: application/json
Accept: text/event-stream, text/event-stream
Cookie: sessionKey={{SESSION}}

{
  "completion": {
    "prompt": "你好",
    "timezone": "Asia/Shanghai",
    "model": "claude-2"
  },
  "organization_uuid": "{{ORGID}}",
  "conversation_uuid": "109d306f-feed-4a54-bebe-28cef16835a5",
  "text": "你好",
  "attachments": []
}

### 查看历史消息
GET {{HOST}}/organizations/{{ORGID}}/chat_conversations/109d306f-feed-4a54-bebe-28cef16835a5
Accept: application/json
Cookie: sessionKey={{SESSION}}

### 重新生成消息
POST {{HOST}}/retry_message
Content-Type: application/json
Accept: text/event-stream, text/event-stream
Cookie: sessionKey={{SESSION}}

{
  "completion": {
    "prompt": "",
    "timezone": "Asia/Shanghai",
    "model": "claude-2"
  },
  "organization_uuid": {{ORGID}},
  "conversation_uuid": "109d306f-feed-4a54-bebe-28cef16835a5",
  "text": ""
}
